openinfradev/tks-flow

decapod-manifests/update-decapod-manifest-wftpl.yaml, deploy_apps/tks-lma-federation-wftpl.yaml, deploy_apps/tks-remove-lma-federation-wftpl.yaml
https://github.com/openinfradev/tks-issues/issues/217
LMA 설치 및 삭제시 thanos endpoint 업뎃하는 과정에서 발생하는 많은 corner case들을 해결하였습니다.
=> handle all corner cases when updating thanos-sc endpoints

github_repo/create-cluster-repo.yaml, github_repo/create-contract-repo.yaml
contract, cluster 생성시 사용하는 git repository 의 privilege 를 private 에서 public 으로 변경합니다.
demo-decapod10 에서 cluster 생성이 실패하기 때문입니다. ( 유료 plan 에서만 org secret 사용 가능한 이슈와 연관 )
=> bugfix. change privilege to public

.github/workflows/lint.yml
(https://github.com/openinfradev/decapod-flow/pull/92 와 동일)
1. `argo template lint` 명령으로 워크플로우템플릿 검증 시 local에 있는 워크플로우템플릿 파일에 경우에도 쿠버네티스 컨피그를 요구함(아래 3과 같은 이유로 추측)
2. 액션 인스턴스에서 접근할 수 있는 쿠버네티스 클러스터가 마땅치 않아 fake kubeconfig를 사용함
3. 워크플로우템플릿이 내부에서 다른 워크플로우템플릿을 호출하는 경우 이 워크플로우템플릿을 쿠버네티스 클러스터에서 찾는데 
4. 이 때마다 fake kubeconfig에 있는 서버로 접근하려 하고 connection refused에러 발생 (https://github.com/openinfradev/decapod-flow/runs/5766950526?check_suite_focus=true)
- CI용 클러스터가 구축됨에 따라(https://github.com/openinfradev/tks-issues/issues/88 ) fake kubeconfig를 CI용 클러스터의 kubeconfig로 교체 
-  kubeconfig에 명시된 user `test`는 존재하지 않는 유저로 쿠버네티스에서 'system:anonymous'권한으로 실행됨
-  `argo template lint`에서 필요한 get workflowtemplate만 수행할 수 있도록 cicd 클러스터에 롤바인딩 적용하여 다른 보안 위협 제거
=> Add kubeconfig for linting workflow template

github_repo/create-cluster-repo.yaml, github_repo/create-contract-repo.yaml
https://github.com/openinfradev/tks-issues/issues/234
tks-user-site-tmpl 대신 통합된 decapod-site 를 사용하도록 수정했습니다.
관련 PR: https://github.com/openinfradev/decapod-base-yaml/pull/161
=> use decapod-site when creating contract repo

github_repo/create-cluster-repo.yaml
클러스터 GIt 저장소 (site and manifests) 생성 과정에서 렌더링이 자동으로 수행됩니다. 현재 설정된 2분 시간으로는 부족한 경우가 많아 불필요하게 워크플루우가 중단되는 경우가 발생하여 데드라인을 5분으로 증가합니다.
=> create-cluster-repo: extend deadline to prevent unnecessary failure

tks-cluster/create-usercluster-wftpl.yaml
clustar-api-aws와 cluster-autoscaler-rbac 를 연속해서 설치하는 기존 방법의 경우 타이밍에 따라 클러스터 네임스페이스가 생성되지 않은 시점에 cluster-autoscaler-rbac가 설치되려고 해서 오류가 발생하는 경우가 있습니다.
이를 방지하기 위해 클러스터 생성 완료 이후에 cluster-autoscaler-rbac 설치를 수행하도록 순서를 변경하였습니다.
=> create-tks-usercluster: change cluster autoscaler rbac installation order

dockerfiles/Dockerfile.e2e-test, tests/tks-e2e.yaml, tks-cluster/validate-usercluster-wftpl.yaml
아래와 같이 TKS 서비스 URL을 입력받아 실행합니다.
```
argo submit --from wftmpl/tks-e2e-test -p tks_info_url=tks-info.svc:9999 -p tks_contract_url=tks-contract.svc:9999 -p tks_cluster-lcm_url=tks-cluster-lcm.svc:999 -n arg
```
E2E 테스트에서 sonobuy 실행하는 템플릿을 호출하기 위해 워크플로우 파라미터를 바로 쓰지 않고 템플릿 파라미터를 사용하도록 변경하였습니다.
=> Add TKS End-to-end test workflow template

github_repo/render-manifests.yaml
endering github action 을 worfklow 로 변경
decapod-render 이미지에 대한 Dockerfile 은 helm2yaml 프로젝트에 있는 Dockerfile 입니다.
2개의 이미지를 하나로 합쳐서 마지막 소스가 위치한 helm2yaml 에 넣었습니다.
테스트 방법
1. admin argo workflow 에 접속
2. workflow template 에서 render-manifests 선택
3. arguments 로 아래 값을 입력
- name: site_name
value: 5b2220b0-39c5-4752-8ecd-d8269c88a3c7
- name: base_repo_url
value: github.com/openinfradev/decapod-base-yaml
- name: base_repo_branch
value: main
- name: site_repo_url
value: github.com/tks-management/5b2220b0-39c5-4752-8ecd-d8269c88a3c7
- name: site_repo_branch
value: main
- name: manifest_repo_url
value: github.com/tks-management/5b2220b0-39c5-4752-8ecd-d8269c88a3c7-manifests
- name: manifest_repo_branch
value: main
=> create new workflow to render manifests

tests/tks-e2e.yaml
https://github.com/openinfradev/tks-issues/issues/283 의 2번 내용 해결.
=> add timeout to busy-wait loops

app_serving/serve-java-app.yaml, dockerfiles/Dockerfile.appserving-worker
app-serving MVP 시연을 위한 workflow 초안 추가합니다. 
우선 신속한 구현을 위해 하나의 step으로 구성되어 있고, 향후 실제 서비스시에는 API 분할에 따라 step이 나뉘어질 것으로 보입니다. 
app profile 선택하는 부분도 현재는 빠져있고 향후 추가 예정입니다.  -> 추가 완료
(update) resource spec도 추가 완료
template은 https://github.com/openinfradev/app-serve-template 에 있습니다.
<참고사항>
- 바로 테스트해보실 수 있게 sample java app을 빌드해놓은 제 개인 repo url 을 default param으로 넣어두었습니다. 
- dockerhub 상에 동적으로 repository를 만들어주어야 100% 자동화가 될텐데, 그부분은 현재 수동으로 수행하였습니다. (차후 harbor 등 다른 Registry를 쓸 수도 있으므로 굳이 Dockerhub API 써서 repo 생성하는 노가다는 하지 않았습니다)
- 마지막의 endpoint 보여주는 부분은 실제 서비스에선 app-serving-LCM 에서 app-serving-CLI로 전달해서 보여줄 내용인데, 아직 해당 컴포넌트들이 없기에 임시로 workflow에 넣어두었습니다.
=> Add app-serving workflow

deploy_apps/tks-lma-federation-wftpl.yaml, deploy_apps/tks-remove-lma-federation-wftpl.yaml, deploy_apps/tks-remove-servicemesh-wftpl.yaml, deploy_apps/tks-service-mesh-dashboard-wftpl.yaml, github_repo/create-cluster-repo.yaml, github_repo/create-contract-repo.yaml, tests/validate-service-wftpl.yaml, tests/validate-usercluster-wftpl.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-cluster/manage-internal-communication.yaml, tks-cluster/remove-usercluster-wftpl.yaml
템플릿 사이트의 인프라 프로바이더 그룹 (tks-cluster-aws or tks-cluster-byoh) 디렉토리를 기준으로 인프라 프로바이더 정보를 얻어서 이후 클러스터 설치 과정에서 사용하도록 하였습니다.
TKS cli는 'template-std' 라는 템플릿 명을 하드코딩 되어 사용하기 있기 때문에 aws, byoh 인프라 프로바이더를 임시적으로 선택해서 설치하기 위해서 https://github.com/openinfradev/tks-flow/commit/a609f1c9faa493169759e84c375fea5ebf44bc30 를 추가하였고 TKS cli에서 클러스터 생성 명령어```tks create cluster```에 템플릿 지정 플래그가 추가되면 되돌리도록 하겠습니다.
**추가 반영한 내용이 있어 업데이트합니다 (2022/06/29)**
- tks cluster lcm에서 infra provider 정보를 유지하지 않기 때문에 임시적으로 삭제 과정에서 내부적으로 인프라 프로바이더 정보를 확인해서 사용하도록 하였습니다: adc6902fa7357116c6012f79039d09dec684b4d9
- cluster-api 를 통해 배포되는 클러스터의 이름을 기존 UUID 모두에서 첫번 째 그룹 (8글자)만 사용하도록 하였습니다: 7093056b33ee64331a68cd6ffa399791cc5fd442
-----
생성되는 클러스터의 인프라 프로바이더 변경을 위해서  ```tks create cluster``` 실행 전 다음 값을 먼저 변경해야 합니다.
- …
=> Supports template configuration with different infrastructure providers

app_serving/serve-java-app.yaml, deploy_apps/tks-ingress-controller-wftpl.yaml, deploy_apps/tks-lma-federation-wftpl.yaml, deploy_apps/tks-remove-lma-federation-wftpl.yaml, deploy_apps/tks-remove-servicemesh-wftpl.yaml, deploy_apps/tks-service-mesh-dashboard-wftpl.yaml, deploy_apps/tks-service-mesh-wftpl.yaml, github_repo/create-cluster-repo.yaml, sealed_secrets/deploy-secrets.yaml, sealed_secrets/setup-sealed-secrets-on-admincluster.yaml, sealed_secrets/setup-sealed-secrets-on-usercluster.yaml, tests/validate-service-wftpl.yaml, tests/validate-usercluster-wftpl.yaml, tks-cluster/aws-infrastructure-wftpl.yaml, tks-cluster/create-aws-infrastructure-w-terraform-wftpl.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-cluster/manage-internal-communication.yaml, tks-cluster/remove-usercluster-wftpl.yaml, tks_info/delete-tks-app-group-wftpl.yaml, tks_info/get-tks-cluster-wftpl.yaml, tks_info/update-tks-app-group-wftpl.yaml, tks_info/update-tks-cluster-status-wftpl.yaml
클러스터 ID 체계가 변경되어 UUID를 사용하지 않기 때문에 관련 수정 사항을 원복합니다.
=> Revert "use the first group of the cluster UUID as the cluster name"

app_serving/serve-java-app.yaml
관련이슈:  https://github.com/openinfradev/tks-issues/issues/307
task_type을 'build', 'deploy', 'all'(build & deploy) 로 바꿔가며 잘 동작하는 것 확인했습니다.
참고로, 각 스텝 분리는 LCM 에서 workflow를 호출하는 인터페이스와도 관련이 있어서 아래 티켓에서 먼저 전체 구조를 고민 후 workflow 작성하였습니다.
https://github.com/openinfradev/tks-issues/issues/309
=> app-serving: build와 deploy 단계 분리

deploy_apps/tks-ingress-controller-wftpl.yaml, github_repo/create-cluster-repo.yaml, github_repo/render-manifests.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-cluster/remove-usercluster-wftpl.yaml
kustomize의  다수의 리소스를 합치는 기능을 활용하여 다양한 변형을 지원할수 있다.
tks-cluster를 만드는 부분에서 infra를 함께 선택하여 aws나 byoh에 적용가능하다. (kustomization.yaml 작성시 포함한다. 다음은 aws 예시)
```
$  cat cluster/kustomization.yaml
resources:
- ../base
- ../infra/aws
transformers:
- site-values.yaml
```
다음 두 pr이 동시 merge되어야 함
- https://github.com/openinfradev/decapod-site/pull/92
- https://github.com/openinfradev/decapod-base-yaml/pull/167
- https://github.com/openinfradev/tks-flow/pull/105
- https://github.com/openinfradev/decapod-flow/pull/96
=> using structured kustomize document on infra-selection

tks-cluster/create-usercluster-wftpl.yaml
local-path를 taco-storage로 사용하기 위한 챠트를 추가합니다.
인프라를 byoh로 지정한 경우 기본으로 설치됩니다.
다음 pr이 함께 merge되야 합니다.
- https://github.com/openinfradev/decapod-base-yaml/pull/166
- https://github.com/openinfradev/tks-flow/pull/102
=> install local-path-provioner for a byoh cluster

app_serving/serve-java-app.yaml, dockerfiles/Dockerfile.appserving-worker, tks_info/update-asa-endpoint-wftpl.yaml, tks_info/update-asa-status-wftpl.yaml
https://github.com/openinfradev/tks-flow/pull/111 PR  + [#306 번 티켓](https://github.com/openinfradev/tks-issues/issues/306) 내용을 합한 PR 입니다.
111번 PR 머지 후에 별도의 PR 올릴까 했으나, 리뷰 두번 요청드리는 것보다 diff가 좀 길어져도 그냥 한번에 끝내는 것이 나을 것 같아 합쳐서 올립니다.  
후자의 내용은 kustomize 기반 manifest 대신 helm chart를 사용하여 배포하도록 변경한 부분입니다. 
helm chart는 https://github.com/openinfradev/app-serve-template 에 들어있습니다.
=> Use helm chart for deployment

github_repo/create-cluster-repo.yaml, github_repo/create-contract-repo.yaml, tks-cluster/create-usercluster-wftpl.yaml
1. 클러스터 생성 워크플로우 호출 시 입력 받은 템플릿 파라미터를 (최초 의도대로) 사용하도록 하였습니다.
2. contract / cluster Git 저장소 생성 할때 META 파일에 원본 Git 저장소 (decapod-site/contract repo) 의 커밋 아이디 등을 남기도록 하였습니다.
=> Cluster template 지원 및 contract/cluster Git 저장소에 META 정보 추가

tests/tks-e2e-aws-msa.yaml, tests/tks-e2e-aws.yaml, tests/tks-e2e-common.yaml
E2E 테스트를 위한 워크플로우 템플릿을 aws-reference, aws-msa-reference 2개의 사이트를 위해 분리하였습니다.
실제로 실행되는 템플릿 정의는 common 워크플로우 템플릿에 두고 각각의 e2e 워크플로우에서 호출하는 형태로 수정하였습니다.
=> tests: seperate e2e test sites into aws and aws-msa

tests/tks-e2e-aws-msa.yaml, tests/tks-e2e-aws.yaml, tests/tks-e2e-common.yaml, tks-cli/tks-cli.yaml, tks-stack/tks-stack-create-aws-msa.yaml, tks-stack/tks-stack-create-aws.yaml, tks-stack/tks-stack-delete-aws-msa.yaml, tks-stack/tks-stack-delete-aws.yaml
클러스터와 서비스를 한 번에 설치하기 위한 스택 워크플로우 템플릿을 추가합니다.
- tks-stack-create-aws: cluster, lma
- tks-stack-create-aws-msa: cluster, lma, service-mesh
e2e 테스트 구현을 재사용하였고 e2e 테스트와 tks stack이 공통으로 사용되는 부분은 tks-cli 워크플로우 템플릿으로 분리하였습니다.
=> tks stack 워크플로우 템플릿 추가

app_serving/delete-java-app.yaml, app_serving/serve-java-app.yaml, tks_info/update-asa-endpoint-wftpl.yaml, tks_info/update-asa-status-wftpl.yaml
관련 이슈:
- update: https://github.com/openinfradev/tks-issues/issues/352
- delete: https://github.com/openinfradev/tks-issues/issues/357
이 중 update 부분은 아래 두 PR과 함께 머지되어야 합니다.
- https://github.com/openinfradev/tks-proto/pull/38 (머지 완료)
- https://github.com/openinfradev/tks-info/pull/46 (머지 완료)
=> App-serving: update 및 delete 로직 구현

github_repo/render-manifests.yaml, tks-cluster/import-usercluster-wftpl.yaml
- render-manifests: manifests 생성 후 main 브랜치에 바로 반영하는 대신 PR 생성하는 기능을 추가하였습니다: Git 저장소가 gitea 경우에만 한정되어 동작합니다 (if 'manifest_repo_branch' is empty and 'git_repo_type' is gitea)
- import-cluster: 갱신 된 render-manifests를 호출하여 manifests 생성 및 저장소 반영이 자동으로 이루어지도록 변경하였습니다.
=> manifests 리뷰용 PR 생성  / 클러스터 import 후 자동 manifests 생성

app_serving/serve-java-app.yaml
https://github.com/openinfradev/tks-issues/issues/413
=> support legacy spring app

tks-cluster/create-usercluster-wftpl.yaml
kubed docker image pull 시 아래와 같은 에러가 발생합니다.
`invalid rootfs in image configuration`
임시 조치로 user 클러스터 생성 flow 에서 kubed 를 삭제합니다. kubed image 가 정상적으로 변경이 될때 이 코멘트 아웃 처리한 부분은 다시 롤백하겠습니다.
=> temporary fix. remove kubed from "create-usercluster-wftpl"

tests/tks-e2e-aws-msa.yaml, tests/tks-e2e-aws.yaml, tests/tks-e2e-common.yaml, tks-cli/tks-cli.yaml
e2e test 실행시 항상 contract 를 신규로 생성하도록 추가합니다.
이 변경으로 decapod-base-yaml, decapod-site 의 변경을 테스트할 수 있습니다.
* contract 조회/삭제는 현재 API 구현이 되지 않은 상태이므로 e2e 테스트에서는 생성된 contract repo 및 db data를 삭제하지 않습니다.
=> add step to tests

git-repo/gitea-sync-mirror.yaml
Gitea의 미러링 저장소 (https://docs.gitea.io/en-us/repo-mirror/#pulling-from-a-remote-repository) 싱크를 수행하는 워크플로우 입니다.
=> add gitea sync mirror workflow

dockerfiles/Dockerfile.tks_aws, git-repo/create-cluster-repo.yaml, tks-cluster/aws-ebs-csi-iam-yaml, tks-cluster/create-aws-conf-secret.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-cluster/remove-usercluster-wftpl.yaml
EKS 클러스터 구성을 위한 수정입니다.
- aws-ebs-csi-driver 는 EKS일 때 설치하지 않음 (EKS Addons로 관리)
- aws-ebs-csi-driver IAM role 설정
- EKS의 kubeconfig를 얻기 위해 기존과 다른 이름의 시크릿 내용을 참조
=> EKS 클러스터 설치 지원

git-repo/event-gitea-render-manifests.yaml, git-repo/gitea-webhook-event-consumer.yaml, git-repo/gitea_webhook_role.yaml, git-repo/render-manifests.yaml
github action 렌더링 워크플로우 동작을 Gitea Webhook과 Argo workflow를 결합하여 구현한 내용입니다.
1. main 브랜치에 push 이벤트 발생 시 Gitea Webhook 발생 (대상: Argo Workflow Event)
2. Argo Workflow 이벤트 컨슈머에서 렌더링 워크플로우 호출
- Webhook에서 전달되는 정보가 렌더링 워크플로우를 바로 호출하기에는 부족하기 때문에 사전 작업을 수행하는 워크플로우 템플릿을 추가하였습니다.
추가로 Git 저장소 서비스 (Gitea or Github URL이 http/https 인 2가지 경우 모두 사용 가능하도록 렌더링 워크플로우를 수정하였습니다.
=> Gitea 렌더링 (site 저장소 -> manifests 저장소) 자동 반영

deploy_apps/tks-lma-federation-wftpl.yaml, deploy_apps/tks-primary-cluster.yaml, dockerfiles/Dockerfile.shyaml, dockerfiles/Dockerfile.tks-api, git-repo/Dockerfile, git-repo/create-cluster-repo.yaml, git-repo/render-manifests.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-cluster/remove-usercluster-wftpl.yaml, tks_info/get-tks-cluster-wftpl.yaml, tks_info/tks-create-tks-api-secret.yaml, tks_info/update-tks-app-group-wftpl.yaml
내부적으로 기존 lma 설치로직에서 호출하며 각 수정은 다음을 포함한다.
- 자신의 조직(org)의 현황에 따라 분기 필요
- 없으면 자기가 primary가 되야 하고 set-primary-cluster 호출
- 이미 primary가 있다면 자신의 설정 중 loki 부분을 변경해야 함
- 입력 파라미터는
- primary_cluster
- member_clusters
- 활용하는 workflow변수는
- organization_id
- cluster id
- tks_info_host
- *일단 상태관련 내역은 추후로 미뤄두고 → 이건 state machine 정의하고 컨세서스 이룬후 진행하는 것이 맞음 (현재 상태는 echo만)*
- 들어오면 namespace 만들어주고
- sub-set-primay-cluster-on-tks-info
- tks-info에 자신을 등록하고.
- sub-change-logging-target
- 필요한 endpoint를 primary에서 구해내고
- 상황에 맞게 update 수행
- 입력변수로 primay_cluster와 member_clusters를 받는데 member_clusters를 조절함으로써 primary가 정해진 상황에서 만들어지는 클러스터에서도 해당 함수를 활용
- tks-lma-federation에서 다음 함수 참조            
```python
- - name: organization-level-update
template: primayCluster
arguments:
parameters:
- name: primary_cluster
value: …
```
=> Primary cluster 생성을 위한 workflow template 추가

git-repo/create-cluster-repo.yaml, tks-cluster/create-usercluster-wftpl.yaml
아래 PR이 먼저 머지되어야 합니다.
* https://github.com/openinfradev/helm-charts/pull/175
* https://github.com/openinfradev/decapod-base-yaml/pull/211
* https://github.com/openinfradev/decapod-site/pull/124
클러스터 생성 시 cloud_account_id 파라미터가 전달된다면 멀티테넌시 클러스터로 생성하며, 그렇지 않은 경우 CAPA 컨트롤러가 사용하는 AWS Credential을 사용하여 (기존 방식) 클러스터를 생성합니다.
=> add support for multi-tenancy aws clusters

app_serving/abort-java-app.yaml, app_serving/delete-java-app.yaml, app_serving/promote-java-app.yaml, app_serving/serve-java-app.yaml, cloud-accounts/aws-multi-tenancy-identity.yaml, deploy_apps/tks-lma-federation-wftpl.yaml, deploy_apps/tks-primary-cluster.yaml, deploy_apps/tks-remove-lma-federation-wftpl.yaml, deploy_apps/tks-remove-servicemesh-wftpl.yaml, deploy_apps/tks-service-mesh-dashboard-wftpl.yaml, dockerfiles/Dockerfile.tks-cluster-init, git-repo/create-cluster-repo.yaml, sealed_secrets/setup-sealed-secrets-on-usercluster.yaml, tests/validate-service-wftpl.yaml, tests/validate-usercluster-wftpl.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-cluster/import-usercluster-wftpl.yaml, tks-cluster/manage-internal-communication.yaml, tks-cluster/remove-usercluster-wftpl.yaml
아래 PR이 먼저 머지되어야 합니다.
* https://github.com/openinfradev/tks-flow/pull/162
Self-managed 컨트롤 플레인, EKS, 멀티 테넌시 등 각각의 상황에 따라 달라지는 kubeconfig 대신 TKS 내부에서 사용할 전용 kubeconfig 시크릿(CLUSTER_ID-tks-kubeconfig)을 생성하고 사용하도록 하였습니다.
=> TKS 내부 사용 Cluster kubeconfig 시크릿 일원화

cloud-accounts/aws-delete-account.yaml, cloud-accounts/aws-multi-tenancy-iam-resources.yaml
클러스터 노드 간 통신을 위해 보안 그룹을 추가할 때 아래와 같이 기존 보안 그룹 정보를 얻어 오는 부분이 존재합니다.
https://github.com/openinfradev/tks-flow/blob/4077fce3e182135ac0266dbfb5948cdc5cb1f7c8/tks-cluster/manage-internal-communication.yaml#L64 
멀티 테넌시 환경에서는 CAPA에서 생성하는 cluster-api 컨트롤러 Role을 사용하며 기본 정책에서 빠져있는 ```ec2:DescribeInstanceAttribute``` 권한을 추가하였습니다.
=> cloud-accouts: add a policy for multi-tenancy

cloud-accounts/aws-create-account.yaml, cloud-accounts/aws-delete-account.yaml, cloud-accounts/aws-multi-tenancy-iam-resources.yaml
클라우드 계정 생성/삭제 시 TKS 계정 정보들은 파라미터 대신 K8S 시크릿을 통해 사용하도록 변경하였습니다.
=> cloud-accounts: use a secret for tks AWS account and user

deploy_apps/tks-lma-federation-wftpl.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-cluster/remove-usercluster-wftpl.yaml
- EKS 클러스터 내부 접근을 위한 kubeconfig 생성 부분의 오류 수정
- EKS에서 불필요한 작업 수행하지 않도록 변경
- EBS CSI 정책은 별도 생성 대신 AWS 내장 정책 사용: https://github.com/openinfradev/decapod-site/pull/129
- kube-proxy 등 메트릭 접근을 위해 보안 그룹은 별도 설정 불필요 (클러스터 노드 간 통신을 위한 전용 보안 그룹 존재)
- LMA: 대상 클러스터가 EKS 인지 확인하는 작업 추가
- EKS 에서는 PV 를 위한 EBS CSI가 애드온을 통해 자동 설치되지만 기본 스토리지 클래스는 gp2 이름으로 생성. TKS 에서 사용하는 스토리지 클래스 이름인 'taco-storage' 로 스토리지 클래스 배포 과정 추가
=> EKS 지원을 위한 수정

deploy_apps/tks-lma-federation-wftpl.yaml, deploy_apps/tks-remove-lma-federation-wftpl.yaml
기존 로직
- grafana 설치 시 client가 있으면 redirectUri 추가 과정 스킵
- grafana 삭제 시 client를 삭제
변경 사항
- grafana 설치 시, client가 있으면 기존 client에 redirectUr를 추가
- grafana 삭제 시, client에 자신을 제외한 다른 endpoint가 있을 시 자신의 endpoint만 제거. 자신이 마지막일 경우 client 삭제
=> bug fix: change keycloak client logic to support multiple uris 

app_serving/serve-java-app.yaml
workflow 상에서 status 업데이트 단계와 endpoint/helm_revision 업데이트 단계의 순서를 서로 맞바꾸도록 수정합니다.
현재 구현 상, B/G 배포의 경우 deploy 단계 완료 후 상태값이 먼저 "BLUEGREEN_WAIT" 로 바뀌어버리면 UI 에서 화면 갱신을 멈춰버리므로, 그 이후에 DB에 업데이트되는 helm_revision 등이 화면에 제대로 갱신되지 않기 때문에 상태값 업데이트를 나중에 하도록 순서를 바꾸는 것입니다.
(이건 quick fix이고 향후 전반적으로 UI와 잘 연계될 수 있도록 상태 관리 체계를 refactoring할 예정입니다.)
어차피 두 단계가 서로 의존성이 없이 독립적이므로 순서를 바꾸는 건 작업 수행상에 특별한 영향도가 없는 걸로 파악됩니다.
=> serve-java-app: change update order

app_serving/abort-java-app.yaml, app_serving/promote-java-app.yaml, app_serving/rollback-java-app.yaml, app_serving/serve-java-app.yaml
API 에서 앱서빙 상태 관리 체계를 단순화함에 따라 workflow도 그에 맞게 수정함
=> app-serving: Refactor stages

cloud-accounts/aws-multi-tenancy-iam-resources.yaml, dockerfiles/Dockerfile.tks_aws, tks-cluster/aws-cluster-autoscaler-iam.yaml, tks-cluster/aws-ebs-csi-iam.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-cluster/remove-usercluster-wftpl.yaml
EKS 에서 클러스터 오토스케일링 지원을 위해 업스트림 차트를 사용해서 cluster-autoscaler를 aws 클라우드 프로바이더 구성으로 배포하도록 한 기존 변경 내역에서 오류를 수정하였습니다.
- EKS IRSA 지원: 클라우드 계정 생성 시 사용자 계정에 생성되는 (TKS에서 위임받아 사용할) controllers.cluster-api-provider-aws.sigs.k8s.io IAM Role에 필요한 Policy 추가
- 기타 오류 수정
=> tks-cluster: fix clusterautoscaler for eks

app_serving/serve-java-app.yaml, tks_info/update-asa-endpoint-wftpl.yaml, tks_info/update-asa-status-wftpl.yaml
AWS 상에 이슈가 있어 LB endpoint가 제대로 할당되지 않을시, workflow를 fail 처리하도록 함.
=> app-serving: make it fail if endpoint is not ready

cloud-accounts/aws-multi-tenancy-iam-resources.yaml
MFA를 사용하지 않는 경우 aws session token 환경 변수가 NULL로 설정됩니다. 워크플로우에서 이를 감지하고 해당 환경 변수 자체를 삭제해야 하는데 불필요한 $ 문자열로 인해 정상 동작하지 않았던 오류를 수정합니다.
=> cloud-accounts: fix to unset aws session token env var

app_serving/serve-java-app.yaml, tks_info/update-asa-endpoint-wftpl.yaml
앱서빙 workflow 수행시 deploy 단계 이후 update-endpoint 단계에서도 로그를 쌓도록 하여, 실제 실패시에 사용자가 마지막 단계의 로그를 볼 수 있도록 함. 
https://github.com/openinfradev/tks-issues/issues/697
=> app-serving: deploy 이후 단계도 로그 기록하도록 수정

tks-cli/tks-cli.yaml
stack을 통해 클러스터 생성할 때 기다리는 시간을 30분에서 60분으로 증가합니다.
=> tks-cli: increase timeout threshold for cluster creation

cloud-accounts/aws-multi-tenancy-iam-resources.yaml
EKS 클러스터 별 IAM Role 생성하도록 Admin 클러스터 계정 환경은 변경하였으나 외부 계정 쪽 설정이 누락된 부분이 있어서 수정하였습니다.
=> cloud-accouts: fix IAM roles per cluster

app_serving/serve-java-app.yaml
legacy spring app 배포를 위해 사용하는 tomcat 차트의 경우, 환경변수를 넣기 위한 value의 구조가 springboot 차트와 다름.  
이 경우 workflow 상에서 인자로 전달받은 환경변수 문자열을 tomcat value 구조에 맞게 후가공해서 사용하도록 함.
https://github.com/openinfradev/tks-issues/issues/753
=> app-serving: override env vars for legacy spring app

git-repo/create-git-repo-svc-token-secret.yaml, git-repo/event-gitea-render-manifests.yaml
렌더링시 webhook 호출의 경우는 branch를 지정해줄수 없습니다.
따라서, 렌더링시 workflow parameter 에 명시적으로 branch 를 지정해주지 않을 경우에는 secret 정보의 값을 사용하여 렌더링 하도록 변경합니다.
@intelliguy 님.
이대로 하면 어떨지 의견 부탁 드립니다.
=> feature. use  branch from secret when decapod rendering.

dockerfiles/Dockerfile.tks_aws, tks-cluster/aws-cluster-autoscaler-iam.yaml
어드민 클러스터가 EKS로 구성된 경우 클러스터 접근 시 aws-iam-authenticator가 필요합니다. 이미지에 누락된  aws-iam-authenticator를 추가합니다.
=> add missing aws-iam-tks-admin-kubeconfig-secret to tks-aws image

deploy_apps/tks-lma-federation-wftpl.yaml, deploy_apps/tks-remove-lma-federation-wftpl.yaml
keycloak의 secret 중 admin 계정/비밀번호를 저장하는 리소스가 있으며, 이 리소스를 활용하는 logic이 존재.
keycloak helm chart 최신화에 따라 secret name이  "credential-tks-keycloak" 에서 "keycloak" 으로 변경되었으며, 이에 따라 필요한 내용 수정함
=> keycloak secret 이름 변경에 따른 수정

deploy_apps/tks-lma-federation-wftpl.yaml, deploy_apps/tks-remove-lma-federation-wftpl.yaml
grafana svc가 생성되지 않았을 때, 비정상 상태임에도 불구하고 정상적으로 진행하던 bug 존재.
수정사항:
grafana svc가 생성되고, loadbalancer type의 external IP가 할당될 때까지 대기 한 후, 남은 로직 진행.
만약, 제한된 시간 내에 값이 추출되지 않을 경우 worflow 실패 처리
=> bug fix: Added error handling for grafana endpoint retrieval

deploy_apps/tks-remove-lma-federation-wftpl.yaml
특정 redirect URI 삭제 과정에서 의도치 않게정상 redirect URI를 포함한 client 자체를 삭제하는 이슈 발생.
이에 대한 방어 로직 추가합니다.
=> bug fix: add safety checks to avoid accidental client removal

app_serving/abort-java-app.yaml, app_serving/delete-java-app.yaml, app_serving/promote-java-app.yaml, app_serving/rollback-java-app.yaml, app_serving/serve-java-app.yaml, deploy_apps/tks-lma-federation-wftpl.yaml, deploy_apps/tks-primary-cluster.yaml, deploy_apps/tks-remove-lma-federation-wftpl.yaml, deploy_apps/tks-remove-servicemesh-wftpl.yaml, deploy_apps/tks-service-mesh-wftpl.yaml, git-repo/create-cluster-repo.yaml, tests/tks-e2e-aws-msa.yaml, tests/tks-e2e-aws.yaml, tks-cli/tks-cli.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-cluster/remove-usercluster-wftpl.yaml, tks_info/delete-tks-app-group-wftpl.yaml, tks_info/get-tks-cluster-wftpl.yaml, tks_info/update-asa-endpoint-wftpl.yaml, tks_info/update-asa-status-wftpl.yaml, tks_info/update-tks-app-group-wftpl.yaml, tks_info/update-tks-cluster-status-wftpl.yaml
- Minimal deploy support
함께 merge되어야 할 것들
- https://github.com/openinfradev/decapod-site/pull/174
- https://github.com/openinfradev/decapod-base-yaml/pull/262
- https://github.com/openinfradev/tks-flow/pull/251
=> 최소사항 클러스터 지원을 위한 여정 #262

git-repo/create-cluster-repo.yaml, tks-cli/tks-cli.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-stack/tks-stack-create.yaml
byoh integration 과정에서 나온 bug fix 들입니다.
=> Byoh integration

deploy_apps/tks-primary-cluster.yaml
clusterapi의 aws와 eks에 대한 머신풀 cr이 다른부분이 있어 이를 모두 확인하도록 하는 기능 추가 (클러스터에 대한 상황체크는 없고 두가지 자원을 모두 체크합니다.)
이에따라 기존 AWSManagedMachinePool 만 체크하던 부분을 AWSManagedMachinePool AWSMachinePool 두가지를 대상으로 하도록 수정합니다,
=> check each type of MachinePool for aws

cloud-accounts/aws-multi-tenancy-iam-resources.yaml
LMA에서 S3 Bucket 접근을 위한 노드 IAM 권한이 필요하고, self-managed control plane인 경우 (aws*-reference 사이트 사용) 해당 내용이 누락되어 있어 추가합니다.
=> cloud-accounts: add S3 full access iam policy for node role

deploy_apps/tks-lma-federation-wftpl.yaml, deploy_apps/tks-primary-cluster.yaml, git-repo/event-gitea-render-manifests.yaml, git-repo/wait-for-redering-to-finish.yaml
decapod 렌더링은 gitea site repo 에 반영(git push)이 이루어지면 webhook을 통해 event-gitea-render-manifests 워크플로우가 실행되어 자동으로 수행하도록 되어 있습니다.
기존 event-gitea-render-manifests을 불필요하게 호출하는 부분을 제거하기 위해서 decapod 렌더링 종료를 대기하는 워크플로우 템플릿(wait-for-rendering-to-finish)을 추가하고 사용하도록 변경하였습니다. 이 변경으로 아래 오류를 발생시켰던 부분은 제거되었습니다.
```
Invalid 'when' expression ''[ "ckrw3g26p" ]' != 'NO_CHANGE_HERE'': Cannot transition token types from STRING [[ ] to VARIABLE [ckrw3g26p]
```
또한, 렌더링 관련 워크플로우 (event-gitea-render-manifests, wait-for-rendering-to-finish)는 정상 종료(Success)된다면, 5초후 자동으로 삭제됩니다.
=> LMA: Decapod 렌더링 대기 워크플로우 템플릿 추가 및 사용

tks-cluster/create-usercluster-wftpl.yaml
어드민 클러스터가 EKS인 경우 kubeconfig 형식/내용이 self-managed 컨트롤 플레인 클러스터와 다르기 때문에 분기해서 처리할 수 있도록 수정하였습니다.
=> fix kubeconfig generation for cluster-autoscaler

app_serving/delete-java-app.yaml
테크 서밋 핸즈온에서 단일 namespace에 복수개의 app을 배포하게 되므로, 앱 삭제시 namespace를 유지하도록 합니다. 
임시 커밋이고, 향후 프로젝트 등 체계 개편 방향에 맞추어 로직을 정할 예정입니다.
=> Preserve namespace on app deletion

tks-cluster/manage-internal-communication.yaml
etcd 메트릭 수집을 위해 2389 포트에 대한 Security rule (ingress)를 추가합니다. (기존 2379는 etcd 간 통신이며 cluster-api-provider-aws에서 이미 관리)
기존 PR 에서 chrry-pick 하여 release branch 로 PR 합니다.
=> fix etcd metrics port for aws security rule

k8s-cli/k8s-cli.yaml, keycloak-client/lib/keycloak-clients.yaml, keycloak-client/lib/keycloak-realms.yaml, keycloak-client/lib/keycloak-users.yaml
누락되었던 도메인 변경 건입니다.
현재는 harbor-cicd 를 harbor 도메인으로 변경해둔 상태입니다.
=> feature. change harbor url to harbor.taco-cat.xyz

deploy_apps/tks-primary-cluster.yaml
아래내역은 세트임
- https://github.com/openinfradev/helm-charts/pull/240
- https://github.com/openinfradev/tks-flow/pull/377
- https://github.com/openinfradev/decapod-site/pull/242
- https://github.com/openinfradev/decapod-base-yaml/pull/323
=> User logging 지원

tks-cluster/create-usercluster-wftpl.yaml
dev 환경은 다름 환경과 admin cluster 의 이름이 다르게 구축되어 있어 develop branch 코드에 적용합니다.
=> trivial. change admin cluster name on dev environment

dockerfiles/Dockerfile.e2e-test, tks-cli/tks-cli.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-stack/tks-stack-create.yaml, tks_info/get-tks-cluster-wftpl.yaml
byoh 스택 생성시, domain 정보를 가져와 tks-endpoint-secret 을 자동으로 생성합니다.
=> feature. create tks-endpoint-secret when cluster creating

git-repo/create-contract-repo.yaml
admin cluster 를 tag 기준(branch가 아닌)으로 셋업할 경우 오류가 발생하는 부분을 수정하였습니다.
@zugwan  HEAD detach 상태에서 remote 로 push 가 되지 않는 현상인데, 이 변경이 맞는건지 체크 바랍니다. 테스트는 완료하였습니다.
=> trivial. rename base branch name for creating contract

tks-cli/tks-cli.yaml, tks-cluster/create-usercluster-wftpl.yaml, tks-cluster/import-usercluster-wftpl.yaml
=> trivial. change max timeout when byoh creating

deploy_apps/tks-primary-cluster.yaml
object store에 대한 수정
1. 근본적으로 이 플로우에서 object store에 대한 조작을 진행함
2. 영향을 받는 부분은 
- loki의 백엔드로서
- prometheus의 장기저장소로서
3. loki 부분은 primary에서만 잘 하면됨
4. prometheus 부분은 맴버 클러스터에서도 어디에 연결되어야 할지 알아야 함
현재 구조는
- default는 s3로 하고 있고
- 사용자가 minio로 지정한 경우 이 설정을 수정하도록 하는 부분이 본 workflow
따라서, 명확하게 minio라고 지정하지 않으면 prometheus 연결에서 문제가 발생할수 있음
다만, 현재의 상황 (primary=aws, member=byoh)에서는 현 pr로 해소됨
(primary=byoh, member=aws)라면 문제가 발생할 것임
현재 byoh가 사용된 케이스(BTV)에서는 항상 endpoint-secret가 존재했으므로 본 로직을 통과하지 않기도 함
=> lma-primary: update logic for object store
