openinfradev/tks-flow

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-service-mesh-wftpl.yaml
- github_repo/create-contract-repo.yaml
- sealed_secrets/setup-sealed-secrets-on-admincluster.yaml
- sealed_secrets/setup-sealed-secrets-on-usercluster.yaml
사이트 이름 변경 (hanu-* -> decapod-*) 입니다.
> change site name to decapod-reference

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
https://github.com/openinfradev/tks-issues/issues/221
- LMA 배포 후 thanos-sidecar의 LB endpoint 를 동적으로 가져오는 부분 추가
- 불필요한 parameter 삭제
테스트 완료하였습니다.
> Get thanos sidecar LB endpoint

- tests/tks-e2e.yaml
ServiceMesh 생성후 validation 체크를 해야 하는데 삭제후 validation 체크를 하도록 되어 있네요.
위치를 변경 합니다.
> bugfix. move servicemesh validation

- deploy_apps/tks-ingress-controller-wftpl.yaml
- github_repo/create-cluster-repo.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- tks-cluster/remove-usercluster-wftpl.yaml
아래 PR들이 먼저 반영되어야 합니다.
1. https://github.com/openinfradev/helm-charts/pull/126
2. https://github.com/openinfradev/decapod-base-yaml/pull/164
3. https://github.com/openinfradev/decapod-site/pull/89
4. https://github.com/openinfradev/decapod-flow/pull/93
기존 cluster-api-aws 차트에서 수행하던 인프라 프로바이더 공통 작업을 템플릿으로 이동하였고 infra_provider 파라미터를 추가하여 프로바이더 별로 분기할 수 있도록 하였습니다.
> support multi cluster api infra providers

- tests/tks-e2e.yaml
workflow duration 이 초 단위로만 보여 가독성을 위해 포맷 수정하였습니다.
> show duration in human-readable manner

- tests/validate-service-wftpl.yaml
- tests/validate-usercluster-wftpl.yaml
clusterId 변경으로 인한 e2e 테스트 에러를 수정합니다.
> bugfix. validation error fix.

- github_repo/create-contract-repo.yaml
이미 @zugwan 님이 알고 계신 내용입니다. bugfix 건.
> bugfix. rename render directory (.github to _github)

- deploy_apps/tks-service-mesh-wftpl.yaml
- tks-cluster/aws-infrastructure-wftpl.yaml
- tks-cluster/create-aws-infrastructure-w-terraform-wftpl.yaml
남아 있는 clusterid 8자리 substr 을 제거합니다.
> bugfix. remove substr function for cluster id

- tks-cluster/remove-usercluster-wftpl.yaml
삭제 대상 클러스터의 인프라 프로바이더 정보 가져오는 부분에 있던 오류를 수정하였습니다.
> remove usercluster: fix getting infra provider of the cluster

- tks-cluster/remove-usercluster-wftpl.yaml
cluster delete 시 argocd 의 app name을 변경합니다.
> bugfix. change argocd app name

- tks-cli/tks-cli.yaml
- tks-stack/tks-stack-create-aws-msa.yaml
- tks-stack/tks-stack-create-aws.yaml
- tks-stack/tks-stack-delete-aws-msa.yaml
- tks-stack/tks-stack-delete-aws.yaml
user cluster creating 시 필요한 contractId, cspId 를 workflow parameter 로 추가하고, buz 로직을 일부분 변경합니다.
> feature. add contractId to workflow template for creating stack

- tks-cli/tks-cli.yaml
- tks-stack/tks-stack-create-aws-msa.yaml
- tks-stack/tks-stack-create-aws.yaml
- tks-stack/tks-stack-delete-aws-msa.yaml
stack 생성시 create 와 description 을 추가합니다.
> Add param to stack

- app_serving/delete-java-app.yaml
- app_serving/serve-java-app.yaml
- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-servicemesh-wftpl.yaml
- deploy_apps/tks-service-mesh-dashboard-wftpl.yaml
- deploy_apps/tks-service-mesh-wftpl.yaml
- github_repo/create-github-token-secret.yaml
- github_repo/render-manifests.yaml
- tests/validate-service-wftpl.yaml
- tests/validate-usercluster-wftpl.yaml
- tks-cli/tks-cli.yaml
- tks-cluster/create-aws-conf-secret.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- tks-cluster/remove-usercluster-wftpl.yaml
워크플로우 이미지 정의에서 불필요한 따옴표 문자 사용을 제거합니다.
> remove unnecessary quote characters from image definitions

- tests/tks-e2e-aws-msa.yaml
- tests/tks-e2e-aws.yaml
unittest 를 위해 workflow 를 수정합니다.
. creator, description 추가
. contractId 추가
> bugfix. fixes unittests

- tks-cluster/import-usercluster-wftpl.yaml
cluster import 를 위한 workflow 를 추가합니다.
> feature. add workflow for import cluster

- deploy_apps/tks-service-mesh-dashboard-wftpl.yaml
금일 수정한 내역입니다.
왜 그런지 정확히는 모르겠지만( 이게 왜 예전에는 되었는지... ) SSL 을 disable 하니 접속이 되네요.
일단 이대로 커밋하고 또다른 이슈가 있는지 추적해봐야겠습니다.
> bugfix. disable ssl for sso

- deploy_apps/tks-service-mesh-dashboard-wftpl.yaml
아 벌써 머지 되었군요.
추가 수정사항입니다. 금일 승규님하고 작업했던 내용중 confidential-port 변경 부분도 추가합니다.
> bugfix. change credential port to 443 from 0

- app_serving/serve-java-app.yaml
https://github.com/openinfradev/tks-issues/issues/410
> Appserving: add PV support

- decapod-manifests/update-decapod-manifest-wftpl.yaml
- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
- tks_info/delete-tks-app-group-wftpl.yaml
- tks_info/get-tks-cluster-wftpl.yaml
- tks_info/update-asa-endpoint-wftpl.yaml
- tks_info/update-asa-status-wftpl.yaml
- tks_info/update-tks-app-group-wftpl.yaml
- tks_info/update-tks-cluster-status-wftpl.yaml
tks-proto 에러 대응을 위한 이미지 업데이트건입니다.
기존의 known-issue 인데 아직 main push 가 되지 않았던 건입니다.
> feature. update docker image from v1 to v2

- github_repo/create-cluster-repo.yaml
control plane 의 값을 1개로 고정하며, 추후 API 에서 변경할 수 있도록 한다.
> feature. add variable for control plane replicas

- app_serving/serve-java-app.yaml
- dockerfiles/Dockerfile.appserving-worker
https://github.com/openinfradev/tks-issues/issues/305
API 로부터 configmap과 secret 내용을 string으로 전달 받아 파일로 쓰고, 이를 helm chart에서 읽어들여서 배포하는 방식으로 구현
> AppServing: handle configmap and secrets

- tks-cluster/create-usercluster-wftpl.yaml
https://github.com/openinfradev/helm-charts/pull/165 수정 사항 중 machinepool 자원 이름이 변경되어 해당 내용을 반영하였습니다.
> tks-cluster: fix wrong machinepool name

- app_serving/abort-java-app.yaml
- app_serving/delete-java-app.yaml
- app_serving/promote-java-app.yaml
- app_serving/serve-java-app.yaml
- dockerfiles/Dockerfile.appserving-worker
- tks_info/update-asa-endpoint-wftpl.yaml
https://github.com/openinfradev/tks-issues/issues/401
> app_serving: implement blue-green deployment

- tks-cluster/create-usercluster-wftpl.yaml
- tks-stack/tks-stack-create-aws-msa.yaml
- tks-stack/tks-stack-create-aws.yaml
ft 테스트중 발생한 이슈들입니다.
특히 kubectl wait --for=condition=Available 이 캐치되지 않는것 같은데 ready 로 변경해야 하는게 아닌지 확인 바랍니다. 2 케이스중 eks 쪽만 변경하였습니다.
> bugfix. minor fixes

- app_serving/serve-java-app.yaml
- decapod-manifests/update-decapod-manifest-wftpl.yaml
- git-repo/create-contract-repo.yaml
- git-repo/delete-cluster-repo.yaml
- git-repo/gitea-sync-mirror.yaml
- git-repo/render-manifests.yaml
- tests/tks-e2e-common.yaml
- tests/validate-service-wftpl.yaml
- tks-cli/tks-cli.yaml
- tks-cluster/aws-ebs-csi-iam.yaml
- tks-cluster/aws-infrastructure-wftpl.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- tks-cluster/import-usercluster-wftpl.yaml
- tks-cluster/manage-internal-communication.yaml
change image url
harbor 에는 변경된 이미지를 업로드 하였음
> change original images url to harbor image url

- git-repo/create-cluster-repo.yaml
- git-repo/create-contract-repo.yaml
- git-repo/create-git-repo-svc-token-secret.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- tks-cluster/remove-usercluster-wftpl.yaml
Gitea를 기본 Git 저장소로 사용하여 프로젝트, 클러스터 site/manifest 저장소로 사용합니다.
> Gitea를 기본 Git 저장소로 사용

- app_serving/abort-java-app.yaml
- app_serving/delete-java-app.yaml
- app_serving/promote-java-app.yaml
- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-servicemesh-wftpl.yaml
- deploy_apps/tks-service-mesh-dashboard-wftpl.yaml
- deploy_apps/tks-service-mesh-wftpl.yaml
- git-repo/create-cluster-repo.yaml
- git-repo/create-git-repo-svc-token-secret.yaml
- git-repo/event-gitea-render-manifests.yaml
- sealed_secrets/deploy-secrets.yaml
- tests/validate-usercluster-wftpl.yaml
- tks-cluster/create-aws-conf-secret.yaml
- tks-cluster/create-aws-infrastructure-w-terraform-wftpl.yaml
- tks-cluster/import-usercluster-wftpl.yaml
- tks-cluster/remove-usercluster-wftpl.yaml
- tks_info/delete-tks-app-group-wftpl.yaml
- tks_info/get-tks-cluster-wftpl.yaml
- tks_info/update-asa-endpoint-wftpl.yaml
- tks_info/update-asa-status-wftpl.yaml
- tks_info/update-tks-app-group-wftpl.yaml
- tks_info/update-tks-cluster-status-wftpl.yaml
> fix missing image url

- git-repo/delete-cluster-repo.yaml
Gitea 대상 클러스터 저장소 삭제 부분을 추가하였습니다.
> Gitea 클러스터 저장소 삭제 수정

- tks-cluster/create-usercluster-wftpl.yaml
- tks-cluster/remove-usercluster-wftpl.yaml
tigera operator를 통한 calico 설치/삭제를 지원하도록 수정하였습니다.
> use tigera-operator for calico installation

- tks-cluster/remove-usercluster-wftpl.yaml
> tks-cluster: fix calico uninstall

- git-repo/render-manifests.yaml
https://github.com/openinfradev/helm2yaml/commits/main 3월 28일에 수정된 내역을 반영한 이미지로 업데이트 합니다.
> update decapod-render to v3.1.2

- tks-cluster/create-usercluster-wftpl.yaml
s3자원에 대한 선언적 관리를 위한 ACK를 추가합니다.
모두 함께 merge되어야 함
- helm: https://github.com/openinfradev/helm-charts/pull/173
- decapod-base: https://github.com/openinfradev/decapod-base-yaml/pull/209
- decapod-site: https://github.com/openinfradev/decapod-site/pull/121
- tks-flow: https://github.com/openinfradev/tks-flow/pull/150
> install ack and their aws resources

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-servicemesh-wftpl.yaml
- dockerfiles/Dockerfile.tks_api
- tks_info/get-tks-cluster-wftpl.yaml
- tks_info/tks-create-tks-api-secret.yaml
- tks_info/update-tks-app-group-wftpl.yaml
하드코딩된 계정 정보를 secret 에서 읽어오도록 변경합니다.
> Tks api migration

- tks-cluster/create-usercluster-wftpl.yaml
- tks-cluster/remove-usercluster-wftpl.yaml
- add delete logic for ack for s3
- add **-crds due to helm bugs
> using aws controller kubernetes for s3

- tests/tks-e2e-aws-msa.yaml
- tests/tks-e2e-aws.yaml
- tests/tks-e2e-common.yaml
- tks-cli/tks-cli.yaml
e2e test 를 위한 test workflow 를 변경합니다.
main test 를 위해 바로 merge 합니다.
> Test tks api

- cloud-accounts/aws-create-account.yaml
- cloud-accounts/aws-delete-account.yaml
- cloud-accounts/aws-multi-tenancy-iam-resources.yaml
- cloud-accounts/aws-multi-tenancy-identity.yaml
- dockerfiles/Dockerfile.tks_aws
멀티 테넌시/클라우드 계정 관련 워크플로우입니다. 생성/삭제(tks-create/delete-aws-cloud-account)를 통해 아래 각 단계 별 내용이 수행됩니다.
1) 전달된 계정 대상으로 CAPA IAM 자원 생성/삭제
2) 어드민 클러스터에 차후 클러스터 생성 시 참조할 수 있는 RoleIdentity 생성/삭제
> add workflow templates for multi-tenancy and cloud account

- tests/tks-e2e-aws-msa.yaml
- tests/tks-e2e-common.yaml
- tks-cli/tks-cli.yaml
organization token 길이 이슈가 해결되어 ,
. e2e 테스트시 organization 을 항상 동적으로 생성하도록 변경합니다.
. organization 을 생성시 cloudAccount 를 dummy 로 생성합니다.
> E2etest auto creating organization

- dockerfiles/Dockerfile.aws_kubectl
- tks-cluster/manage-internal-communication.yaml
멀티테넌시 클러스터의 노드에 추가 보안 그룹을 설정하기 위해 aws sts assule-role 을 사용, 임시 자격을 획득하는 부분을 추가하였습니다.
> tks-cluster: use sts assume-role to access multitenancy AWS resources

- git-repo/create-cluster-repo.yaml
사용하지 않는 Decapod 글로벌 변수를 삭제합니다.
> git-repo: remove a unused decapod global variable

- app_serving/delete-java-app.yaml
- app_serving/promote-java-app.yaml
- app_serving/rollback-java-app.yaml
- app_serving/serve-java-app.yaml
- tks_info/update-asa-endpoint-wftpl.yaml
- tks_info/update-asa-status-wftpl.yaml
set deployment's replicas to 0
refactoring rollout
add to delete rollout
fix promote and abort rollout
update helm revision when promote or abort
add org id
hardening delete logic
fix abort and undo
add rollback
fix update status
> change to update appserve status and endpoint and to build image

- tks-cluster/create-usercluster-wftpl.yaml
EKS 클러스터 생성 시 잘못된 if 문과 들여쓰기를 수정하였습니다.
> fix indentation and incorrect if statements when creating eks cluster

- tks-stack/tks-stack-create-aws.yaml
bugfix. 스택 생성시 workflow parameter 추가
> bugfix. add params for creating stack

- tks-cluster/create-usercluster-wftpl.yaml
tks-ingressgateway=enabled
tks-egressgateway=enabled
tks-msa=enabled
> change msa node labels

- tks-cluster/create-usercluster-wftpl.yaml
아래 3개를 모두 같이 merge 해야 함
- decapod-base-yaml
- decapod-site
- tks-flow
> add argo-rollouts

- git-repo/create-contract-repo.yaml
lma/site-values.yaml에 아래 두가지 global 변수 추가
- keycloakDomain
- realms
해당 변수들을 통해 stack 생성 시 keycloak 주소가 정상적으로 입력되도록 함
> create-contract-repo: add keycloak url 

- deploy_apps/tks-primary-cluster.yaml
mutex추가 합니다. api서버혹은 argo를 통해 동시 lma 설치해도 primary 설정 갭에따른 장애는 제거됨
> primary-cluster: add mutex with organization_id for synchronization

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-servicemesh-wftpl.yaml
- deploy_apps/tks-service-mesh-wftpl.yaml
- git-repo/create-contract-repo.yaml
LMA 설치 이후 과정에서 Keycloak에 client를 생성, Grafana 서버 설정에 대한 workflow 추가
> Grafana SSO 관련 기능 추가

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-primary-cluster.yaml
alertmanager에 설정한 구체적인 url은 workflow 실행시 파라미터로 받습니다.
> alertmanager: configure alertmanager eps upon parameters

- deploy_apps/tks-lma-federation-wftpl.yaml
- git-repo/create-contract-repo.yaml
- git-repo/render-manifests.yaml
- tks_info/update-tks-app-group-wftpl.yaml
- 추가 기능: LMA 구성 후 Grafana endpoint를 tks-api 통해 DB에 반영
- tks-api의 app-group API 요청 body에 맞게 일부 수정
> Grafana Client 설정 및 Endpoint TKS api DB에 반영

- tks-cluster/aws-cluster-autoscaler-iam.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- tks-cluster/remove-usercluster-wftpl.yaml
EKS 클러스터 오토스케일링 지원을 위한 수정입니다.
- 기존 TKS 내부 cluster-autoscaler 차트 대신 업스트림 차트 사용
- cluster-autoscaler 동작에 필요한 IAM 정책및 IRSA 구성
> ESK cluster autoscaler 지원

- app_serving/serve-java-app.yaml
https://github.com/openinfradev/tks-issues/issues/678
> app-serving: use rollout file based on app_type

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
endpoint 값 자체에 "/*"을 붙여 다음 workflow에 넘겨주며 문제 발생. 이로인해 grafana 설정 파일에 잘못된 값이 설정됨.
문제 발생 부분 수정
> bug fix: fix wrong endpoint handling

- tks-cluster/aws-cluster-autoscaler-iam.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- tks-cluster/remove-usercluster-wftpl.yaml
- 사용자에게 배표할 클러스터 kubeconfig를 CLUSTER_ID-tks-user-kubeconfig 라는 이름으로 생성하도록 하였습니다.
- cluster-autoscaler aws 클라우드 프로바이더 지원 관련 오류를 수정하였습니다.
> tks-user-kubeconfig 추가 및 cluster-autoscaler 오류 수정

- app_serving/serve-java-app.yaml
https://github.com/openinfradev/tks-issues/issues/697
> app-serving: handle case that update-endpoint stage fails

- app_serving/promote-java-app.yaml
- app_serving/rollback-java-app.yaml
- app_serving/serve-java-app.yaml
- tks_info/update-asa-endpoint-wftpl.yaml
앱서빙의 task별 로그 최상단에 수행 중인 workflow name 을 포함하여, 세부 디버깅시 매핑된 workflow를 쉽게 찾을 수 있도록 한다.
> app-serving: include workflow name in log

- app_serving/delete-java-app.yaml
- app_serving/serve-java-app.yaml
spring 타입의 경우 리소스 스펙이 제대로 override가 안되고 있는 이슈 fix!
> bugfix: app-serving: override tomcat resources

- app_serving/serve-java-app.yaml
https://github.com/openinfradev/tks-issues/issues/707
> app-serving: check endpoint reachability

- app_serving/serve-java-app.yaml
> bugfix: fix typo

- app_serving/serve-java-app.yaml
https://github.com/openinfradev/tks-issues/issues/725
> bugfix: appserving: increase LB timeout

- deploy_apps/tks-remove-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-servicemesh-wftpl.yaml
appgroup 삭제시에도 branch 입력받도록 파라미터 추가함.
사유 : lma 삭제시에도 rendering 이 필요해짐.
> trivial. add workflow paramters to remove appgroup

- tests/tks-e2e-aws-msa.yaml
- tests/tks-e2e-aws.yaml
- tests/validate-usercluster-wftpl.yaml
- tks-cli/tks-cli.yaml
- tks-cluster/create-usercluster-wftpl.yaml
e2e 테스트를 현행화 합니다.
. tks-cli 변경 적용
. interface 변경등에 따른 픽스들입니다.
소노보이 테스트는 계속 실패하고 있어, 해당 부분 코멘트하여 일단 PR 합니다.
> feature. e2e test changes

- tests/tks-e2e-aws-msa.yaml
- tests/tks-e2e-aws.yaml
e2e테스트의 validate cluster 주석을 해제하였습니다.
> remove comments

- tests/validate-service-wftpl.yaml
> trivial. change namespace to "tks-msa" for e2e testing

- app_serving/serve-java-app.yaml
release 에서는 app-serve-template의 release 브랜치를 바라보도록 싱크 맞춤.
> use release branch of app-serve-template

- deploy_apps/tks-lma-federation-wftpl.yaml
tks-lma-federation 에서 호출하는데 그곳에 빠져있었네요.
> s3support: add missed volume in tks-lma-federation

- tks-cluster/create-usercluster-wftpl.yaml
workflow 에 명시적인 syntax error 가 있어 수정합니다.
> bugfix. fix workflow syntax error

- deploy_apps/tks-primary-cluster.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
> s3support: delete objects on each bucket before deleting

- deploy_apps/tks-remove-lma-federation-wftpl.yaml
> delete loki before deleting buckets

- cloud-accounts/aws-multi-tenancy-iam-resources.yaml
- deploy_apps/tks-primary-cluster.yaml
- tks-cluster/aws-cluster-autoscaler-iam.yaml
- tks-cluster/create-aws-conf-secret.yaml
awsconfig-secret 시크릿에 AWS config, credential, account id, user 정보를 모두 담도록 수정하였습니다.
> AWS 계정 정보를 단일 시크릿으로 통합

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-primary-cluster.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
사용하는 kubeconfig 변경관련 pr입니다.
clusterid-kubeconfig => clusterid-tks-kubeconfig
> deploy_apps: using clusterid-tks-kubeconfig

- deploy_apps/tks-remove-lma-federation-wftpl.yaml
> remove lma: delete loki and bucket only for  primary cluster

- deploy_apps/tks-primary-cluster.yaml
> deploy workload for removing buckets on the user cluster

- deploy_apps/tks-primary-cluster.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
piggyback - ignore error when loki dose not exist
- volume명 잘못준것 수정했고
- 내부 실행시 기본적으로 네임스페이스를 argo로 주는 것 같아서 lma 사용하도록 강제했고
- 두번 실행시 loki가 먼저 지워져 수행이 안되는 상황 해소를 위해 ignore 추가
> bugfix: fix a volume name, namespace and so on.

- git-repo/create-cluster-repo.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- TKS API에서 가져오는 cluster info를 통해 클러스터 엔드포인트가 사이트 변수에 설정될 수 있도록 추가
- TKS 노드에 LMA, Service mesh 등을 배포하기 위한 노드 레이블 설정 단계 추가
> BYOH 클러스터 엔드포인트 구성 및 TKS 노드 레이블 설정 추가

- git-repo/create-cluster-repo.yaml
클러스터 노드 숫자 설정을 인프라 프로바이더 별로 분리하지 않고 공통 기능으로 변경하였습니다.
> make cluster node count settings a common feature

- tks-cluster/create-usercluster-wftpl.yaml
> bugfix. wait until the node is completely created

- tks-cluster/create-byoh-bootstrapkubeconfig.yaml
BYOH 사용자 클러스터 지원을 위한 워크플로우입니다.
사용자 클러스터의 Bootstrap Kubeconfig 생성 및 agent 설치 스크립트를 Gitea에 업로드 하는 내용입니다.
> tks-cluster: add workflows for byoh bootstrap kubeconfig

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-primary-cluster.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
- tks-cluster/create-usercluster-wftpl.yaml
EP용 Secret이 존재한다면 이를 통해 endpoint를 판단하는 로직 추가.
endpoint에 기록된 해당 서비스의 endpoint가 모든 정보에 우선한다.
> Endpoint용 Secret 활용

- deploy_apps/tks-primary-cluster.yaml
- tks-cluster/create-usercluster-wftpl.yaml
> create the secret for eps to support byoh

- tks-cluster/create-usercluster-wftpl.yaml
> typo: update indent and the secret name.

- tks-cluster/create-usercluster-wftpl.yaml
> triv: update parameter for json parsing

- tks-cluster/create-usercluster-wftpl.yaml
> ep-secert: update ep name

- tks-cluster/create-usercluster-wftpl.yaml
> trivial. add metrics-server to install-addons-byoh workflow

- deploy_apps/tks-primary-cluster.yaml
> bugfix: change the condition

- git-repo/render-manifests.yaml
- tks-cluster/import-usercluster-wftpl.yaml
import cluster 기능 구현
. kubeconfig 를 입력으로 k8s 외부 cluster 를 tks 내의 클러스터 체계로 구성한다.
> Import cluster

- deploy_apps/tks-lma-federation-wftpl.yaml
> bugfix: escape error in creating a byoh cluster.

- git-repo/render-manifests.yaml
@zugwan.
byoh render 실패를 회피하기 위해 무식하게 분기 조건을 추가하였습니다.
이 부분 관련하여 re-architecturing 이 필요하다고 하셨는데, 그 전의 임시 처리입니다.
확인 부탁 드립니다.
> workaround. add condition to render workflow.

- tks-cluster/remove-usercluster-wftpl.yaml
@zugwan 님.
byoh 타입일 경우, local-path-provisioner 를 추가하였습니다.
검토 부탁 드립니다.
> bufix. add delete local-path-provisioner stage to delete cluster

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-primary-cluster.yaml
if문의 테스트 스타일을 [ a = b ]에서  [[ a == b ]]으로 변경
문의하신 것의 직접적인 버그부분은 == 조건을 줘야하는데 != 조건이 들어가 적용이 안됐던 내역입니다.
> bugfix: change test style in bash and corret bugs

- deploy_apps/tks-lma-federation-wftpl.yaml
syntax 에러가 발생하여 수정합니다. 
테스트한 코드는 아니므로, 감안하여 리뷰 부탁 드립니다.
> bugfix. fix typo

- tks-admin-cluster/tks-install-admin-tools.yaml
2023.11.01 SKB 환경에서 admin cluster 2차 구축 과정에서 나온 필요 수정 사항을 반영하였습니다.
> minor modification for skb installation

- git-repo/render-manifests.yaml
https://github.com/openinfradev/helm2yaml/pull/10 참조
> Crd 추출방식 변경을 반영... 이미지 버전업

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-primary-cluster.yaml
- 포함된 클러스터 id를 파라미터로 사용시 문제가 발생하던 부분에 대한 수정
> Change custerid schema

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-primary-cluster.yaml
- git-repo/render-manifests.yaml
> Resolve conflict

- deploy_apps/tks-lma-federation-wftpl.yaml
> deploy_apps: lma: fix syntax and typo errors

- deploy_apps/tks-lma-federation-wftpl.yaml
@intelliguy 님이 변경하신 byoh향 코드가 기존 public service 에 영향이 있어 @zugwan 님이 변경하셨습니다.
해당 코드를 다시 release 에서 검증하니 byoh 에서 다시 오류가 발생하였습니다.
btv 설치를 위해 v3.1.1 에 아래와 같이 적용하려고 합니다. 확인 부탁 드립니다.
아래 코드로 byoh 테스트 완료하였습니다.
> bugfix. workaround fix for byoh. MUST be fixed for AWS.

- deploy_apps/tks-primary-cluster.yaml
decapod-site에 관련 설정을 반영(https://github.com/openinfradev/decapod-site/pull/203/files) 하였으나 tks-flow에서 해당 영역 전체를 초기화 (아래 내역) 하고 변수들을 재 설정하는 부분이 있어 무효화되는 문제가 있습니다. 재구성 하는 부분에 관련 변수 설정을 추가합니다.
- https://github.com/openinfradev/tks-flow/blob/develop/deploy_apps/tks-primary-cluster.yaml#L361
- https://github.com/openinfradev/tks-flow/blob/develop/deploy_apps/tks-primary-cluster.yaml#L646
> deploy_apps: lma:  fix thanos storegateway permissions for S3

- git-repo/create-contract-repo.yaml
기존의 4개의 site에 대해서만 동작하던 로직을 -reference로 끝나는 디렉토리 모두에 동작하도록 수정하였습니다.
> bugfix. change static keycloak domain render directory to dynamic

- tks-cluster/remove-usercluster-wftpl.yaml
cluster-autoscaler 삭제 조건이 잘못된 부분을 수정합니다.
> fix condition for removing cluster-autoscaler

- git-repo/render-manifests.yaml
https://github.com/openinfradev/helm2yaml/pull/12 내용이 포함된 v3.3.0 버전으로 변경합니다.
> render: update render to v3.3.0

- tks-admin-cluster/tks-install-admin-tools.yaml
bugfix 건입니다. 반영후 바로 main 반영하겠습니다.
> bugfix. change variable "postgresql-password" to "postgre-password"

- tks-admin-cluster/tks-install-admin-tools.yaml
- tks-cluster/create-usercluster-wftpl.yaml
> 20231109 release to main

- tks-cluster/create-usercluster-wftpl.yaml
https://github.com/openinfradev/helm-charts/pull/217/files 관련된 수정입니다. 서비스 어카운트 토큰 가져오는 부분을 수정하였습니다.
> Fix cluster autoscaler serviceaccount token

- tks-cluster/create-usercluster-wftpl.yaml
https://github.com/openinfradev/tks-flow/pull/317 내용 중 오류를 수정합니다.
> tks-cluster: fix an admin cluster type check error

- deploy_apps/tks-service-mesh-wftpl.yaml
Kiali & Jaeger SSO 동작에 대해 6시 경 테스트에서 나온 내용 fix 하였습니다.
> bug fix: reordering wf to make kiali secret before running pod

- git-repo/create-cluster-repo.yaml
byoh 테스트중 렌더링 오류가 발생하여 수정하였습니다.
> bugfix. fix rendering error

- app_serving/delete-java-app.yaml
- git-repo/create-cluster-repo.yaml
231120 release to main ( v3.1.2 )
> 231120 release to main ( v3.1.2 )

- app_serving/delete-java-app.yaml
- git-repo/create-cluster-repo.yaml
231120 main to develop back merge ( v3.1.2 )
> 231120 main to develop back merge ( v3.1.2 )

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-policy-wftpl.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- https://github.com/openinfradev/tks-flow/pull/256
- https://github.com/openinfradev/decapod-flow/pull/130
- https://github.com/openinfradev/decapod-base-yaml/pull/265
- https://github.com/openinfradev/decapod-site/pull/178
- https://github.com/openinfradev/helm-charts/pull/216
> Policy serving

- tks-cluster/aws-cluster-autoscaler-iam.yaml
cluster-autoscaler IRSA 사용을 위해 생성하였던 EKS OIDC 프로바이더와 IAM Role 등을 제거하도록 수정하였습니다.
> add missing oidc provider deletion

- app_serving/abort-java-app.yaml
- app_serving/delete-java-app.yaml
- app_serving/promote-java-app.yaml
- app_serving/rollback-java-app.yaml
- app_serving/serve-java-app.yaml
- tks_info/update-asa-endpoint-wftpl.yaml
- tks_info/update-asa-status-wftpl.yaml
appserving이 project 하위로 이동되는 리팩토링 시 누락된 파라미터들 추가
> app-serving: add missing param 'project_id'

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-primary-cluster.yaml
- tks-cli/tks-cli.yaml
- tks-cluster/aws-cluster-autoscaler-iam.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- tks-stack/tks-stack-create.yaml
- tks_info/get-tks-stack-template-wftpl.yaml
- tks_info/tks-check-node.yaml
> feature. add policy for creating stack

- keycloak-client/lib/keycloak-clients.yaml
- keycloak-client/lib/keycloak-realms.yaml
- keycloak-client/lib/keycloak-users.yaml
- keycloak-client/set-user-cluster.yaml
- tks-cluster/aws-eks-keycloak-oidc-provider.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- tks-cluster/import-usercluster-wftpl.yaml
> add keycloak setting during importing k8s cluster

- deploy_apps/tks-lma-federation-wftpl.yaml
- deploy_apps/tks-remove-lma-federation-wftpl.yaml
tks-endpoint-secret에 grafana 에 대한 값이 없을 경우, Loadbalancer로부터 endpoint를 가져오도록 수정
> bugfix. use grafana ep retrieved from loadbalancer

- deploy_apps/tks-policy-wftpl.yaml
cr을 만드는데 labels: 라인이 삭제된 내역 수정
error: error parsing /tks_cluster_c88i17kt1.yaml: error converting YAML to JSON: yaml: line 8: did not find expected key
> policy: bugfix on cluster cr

- tks-cluster/create-usercluster-wftpl.yaml
multi -l options are working as OR condition not AND
결국은 두번검사를 통해 대상 네임스페이스를 정해야 하네요..
> policy: bugfix to find policy namespace

- deploy_apps/tks-policy-wftpl.yaml
> Fix policy

- deploy_apps/tks-policy-wftpl.yaml
- tks-cluster/aws-cluster-autoscaler-iam.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- tks_info/apply-policies.yaml
. 스택 삭제시 에러 버그픽스
. 스택 생성시 정책 적용 스텝 추가
> feature. add applying policy step when creating stack

- deploy_apps/tks-policy-wftpl.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- tks_info/apply-policies.yaml
> trivial. bugfix for creating stack

- tks-cluster/remove-usercluster-wftpl.yaml
스택 삭제시 policy 관련 argo app 을 삭제하도록 추가합니다.
aws, byoh 모두 가능한 케이스로 보고 when 조건문은 추가하지 않습니다.
> feature. remove policies argo apps when stack deleting

- tks-cli/tks-cli.yaml
누락된 parameter 추가 ( policy-ids )
> tirivial. add policy_ids to createCluster workflow

- tks-cli/tks-cli.yaml
> trivial. fix typo

- deploy_apps/tks-remove-lma-federation-wftpl.yaml
> feature. fix typo

- tks-cluster/create-usercluster-wftpl.yaml
> trivial. remove test code

- k8s-cli/k8s-cli.yaml
- tks-cluster/create-usercluster-wftpl.yaml
- tks-cluster/import-usercluster-wftpl.yaml
- tks-cluster/remove-usercluster-wftpl.yaml
@intelliguy 성일님, OPA Gatekeeper 설치시 secret으로 account 정보(orgId, clusterId, accountId, password) 저장하도록 작성하였습니다.
> Create secret including account information for opa gatekeeper

- tks-cluster/remove-usercluster-wftpl.yaml
삭제시 policy cr 의 finalizer 를 삭제합니다. (workaround)
> feature. add step for unsetting policy crs

- deploy_apps/tks-primary-cluster.yaml
아래내역은 세트임
- https://github.com/openinfradev/helm-charts/pull/240
- https://github.com/openinfradev/tks-flow/pull/377
- https://github.com/openinfradev/decapod-site/pull/242
- https://github.com/openinfradev/decapod-base-yaml/pull/323
- https://github.com/openinfradev/decapod-flow/pull/144
> user logging 지원

- deploy_apps/tks-primary-cluster.yaml
아래내역은 세트임
- https://github.com/openinfradev/helm-charts/pull/240
- https://github.com/openinfradev/tks-flow/pull/377
- https://github.com/openinfradev/tks-flow/pull/379
- https://github.com/openinfradev/tks-flow/pull/380
- https://github.com/openinfradev/decapod-site/pull/242
- https://github.com/openinfradev/decapod-base-yaml/pull/323
- https://github.com/openinfradev/decapod-flow/pull/144
> user logging: add installation for loki-user

- deploy_apps/tks-primary-cluster.yaml
- tks-cli/tks-cli.yaml
- tks-cluster/import-usercluster-wftpl.yaml
- tks-stack/tks-stack-import.yaml
> feature. add endpoint secret creation step when importing

- deploy_apps/tks-primary-cluster.yaml
- tks-cluster/create-usercluster-wftpl.yaml
> 20241002 release from develop

- tks-cli/tks-cli.yaml
- tks-cluster/create-usercluster-wftpl.yaml
> 241017 main from release
